### PR TITLE
Lookup attribute using nix-env

### PR DESCRIPTION
**Pull request by matthewbauer**
This should improve results especially with finding attributes. Sadly lookups with 'nix-env' are extremely slow. This gives us more accurate results though.

### CODE REVIEW

**Comment by ryantm** [comment]
I thought there was something about adding a cache in nix 2.0.

**Comment by matthewbauer** [comment]
> I thought there was something about adding a cache in nix 2.0.

```nix search``` does this but there's not an option to just search by 'name' which is what ```nix-env -qa``` can do.

**Comment by matthewbauer** [comment]
I had lots of success with this method. It should be okay to merge if it looks okay to you.

**Comment by ryantm** [comment]
Looks good! Thanks

**Pull request merged**
